#!/bin/bash
./liquibase --changeLogFile=changelog/changelog.xml \
--username="usuario" \
--password="senha" \
--url=jdbc:mysql://"endereco do banco de dados" \
--driver=com.mysql.jdbc.Driver \
--defaultSchemaName=liquibase \
--classpath=src/mysql-connector-java-5.1.13.jar \
--driver=com.mysql.jdbc.Driver \
 ${1} \
 ${2}

